feat: get payment gateways from ERPNext
phot0n/frappe_payments pull request #44
Opened 2023-09-21 01:54 UTC by s-aga-r

2023-09-21 04:04 UTC, ankush commented
Base branch seems to be messed up? Why is it showing these many commits. 


Maybe rebase it on latest develop branch.

2023-09-21 06:14 UTC, s-aga-r commented
> Base branch seems to be messed up? Why is it showing these many commits.
> 
> Maybe rebase it on latest develop branch.

FF Rebase won't work, had too many changes in the last 5 years. 

OR we can move without history.

2023-09-26 05:36 UTC, s-aga-r commented
@ankush 

Two blockings here:
- `GoCardless Settings` creates `GoCardless Mandate` and `GoCardless Mandate` has a Link field for `ERPNext Customer`. We can create a custom field on installation (?)
- `test_mpesa_settings.py` requires `create_pos_invoice` from ERPNext.

2023-10-14 09:26 UTC, blaggacao commented
Maybe `validate_transaction_currency` weirdly called by `erpnext.accounts.doctype.payment_request.payment_request.{get_request_acount,get_payment_url}` and `validate_minimum_transaction_amount` called by `[idem].get_payment_url` should both be folded into `on_payment_request_submission`, instead?

This would reduce the api interface to the necessary minimum and along with https://github.com/frappe/erpnext/pull/37503 would make this refactoring a bit more polished.

2023-10-14 09:28 UTC, blaggacao commented on payments/payment_gateways/doctype/gocardless_settings/gocardless_settings.py
> +			)
Should be folded into `on_payment_request_submission`

2023-10-14 09:34 UTC, blaggacao requested changes
Unless this refactoring is barred from orthogonal improvements / changes. According to above comment, I suggest to:

- Standardize around `on_payment_request_submission` hook for `validate_transaction_currency` & `validate_minimum_transaction_amount` (and all other relevant validations)
- Consequentially, throw on `payment_gateway_validation` instead of casting any errors into silence by default (callers can do so if they so require).
- Amplify the API with `on_payment_authorized_redirect` as described in the linked PR
- Maybe even reduce the interface around `controller.request_for_payment(**payment_record)`

If this refactoring is barred from these changes, in order to facilitate a coordinated implementation, I'd suggest to address these issues before the refactoring is completed in order to avoid having to coordinate an API refactoring across repositories later.

2023-10-14 09:34 UTC, blaggacao commented on payments/payment_gateways/doctype/mpesa_settings/mpesa_settings.py
> +			)
Should be folded into `on_payment_request_submission`.

2023-10-14 11:16 UTC, s-aga-r commented
@blaggacao do changes separately once this PR is merged.

2023-10-14 11:17 UTC, merged